# Generated by Django 2.2 on 2020-12-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201208_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='invested_balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
