# Generated by Django 2.2 on 2020-12-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20201212_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin_count_clicker',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
