# Generated by Django 2.2 on 2020-12-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20201214_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(default='Level 1', max_length=50),
            preserve_default=False,
        ),
    ]
